apiVersion: apps/v1
kind: Deployment
metadata:
  name: testimage-deployment
  namespace: test-isstream
spec:
  template:
    spec:
      containers:
      - name: test
        image: approved-apache:2.4
