apiVersion: apps/v1
kind: Deployment
metadata:
  name: testimage-deployment
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: test
        image: approved-apache:2.4
