apiVersion: apps/v1
kind: Deployment
metadata:
  name: testimage-deployment
  namespace: test-isstream
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: test
        image: approved-apache:test
